//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name QuestionsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Questions", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference1.QuestionsResponse Questions(WindowsFormsApplication1.ServiceReference1.QuestionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Questions", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.QuestionsResponse> QuestionsAsync(WindowsFormsApplication1.ServiceReference1.QuestionsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuestionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Questions", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.QuestionsRequestBody Body;
        
        public QuestionsRequest() {
        }
        
        public QuestionsRequest(WindowsFormsApplication1.ServiceReference1.QuestionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QuestionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id;
        
        public QuestionsRequestBody() {
        }
        
        public QuestionsRequestBody(int a, int id) {
            this.a = a;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuestionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QuestionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.QuestionsResponseBody Body;
        
        public QuestionsResponse() {
        }
        
        public QuestionsResponse(WindowsFormsApplication1.ServiceReference1.QuestionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QuestionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QuestionsResult;
        
        public QuestionsResponseBody() {
        }
        
        public QuestionsResponseBody(string QuestionsResult) {
            this.QuestionsResult = QuestionsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsApplication1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference1.WebService1Soap>, WindowsFormsApplication1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.QuestionsResponse WindowsFormsApplication1.ServiceReference1.WebService1Soap.Questions(WindowsFormsApplication1.ServiceReference1.QuestionsRequest request) {
            return base.Channel.Questions(request);
        }
        
        public string Questions(int a, int id) {
            WindowsFormsApplication1.ServiceReference1.QuestionsRequest inValue = new WindowsFormsApplication1.ServiceReference1.QuestionsRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.QuestionsRequestBody();
            inValue.Body.a = a;
            inValue.Body.id = id;
            WindowsFormsApplication1.ServiceReference1.QuestionsResponse retVal = ((WindowsFormsApplication1.ServiceReference1.WebService1Soap)(this)).Questions(inValue);
            return retVal.Body.QuestionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.QuestionsResponse> WindowsFormsApplication1.ServiceReference1.WebService1Soap.QuestionsAsync(WindowsFormsApplication1.ServiceReference1.QuestionsRequest request) {
            return base.Channel.QuestionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.QuestionsResponse> QuestionsAsync(int a, int id) {
            WindowsFormsApplication1.ServiceReference1.QuestionsRequest inValue = new WindowsFormsApplication1.ServiceReference1.QuestionsRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.QuestionsRequestBody();
            inValue.Body.a = a;
            inValue.Body.id = id;
            return ((WindowsFormsApplication1.ServiceReference1.WebService1Soap)(this)).QuestionsAsync(inValue);
        }
    }
}
