//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name AnswerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Answer", ReplyAction="*")]
        ConsoleApplication1.ServiceReference1.AnswerResponse Answer(ConsoleApplication1.ServiceReference1.AnswerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Answer", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.AnswerResponse> AnswerAsync(ConsoleApplication1.ServiceReference1.AnswerRequest request);
        
        // CODEGEN: Generating message contract since element name QuestionsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Questions", ReplyAction="*")]
        ConsoleApplication1.ServiceReference1.QuestionsResponse Questions(ConsoleApplication1.ServiceReference1.QuestionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Questions", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.QuestionsResponse> QuestionsAsync(ConsoleApplication1.ServiceReference1.QuestionsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnswerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Answer", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference1.AnswerRequestBody Body;
        
        public AnswerRequest() {
        }
        
        public AnswerRequest(ConsoleApplication1.ServiceReference1.AnswerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnswerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id;
        
        public AnswerRequestBody() {
        }
        
        public AnswerRequestBody(int a, int id) {
            this.a = a;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnswerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnswerResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference1.AnswerResponseBody Body;
        
        public AnswerResponse() {
        }
        
        public AnswerResponse(ConsoleApplication1.ServiceReference1.AnswerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AnswerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AnswerResult;
        
        public AnswerResponseBody() {
        }
        
        public AnswerResponseBody(string AnswerResult) {
            this.AnswerResult = AnswerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuestionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Questions", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference1.QuestionsRequestBody Body;
        
        public QuestionsRequest() {
        }
        
        public QuestionsRequest(ConsoleApplication1.ServiceReference1.QuestionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QuestionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id;
        
        public QuestionsRequestBody() {
        }
        
        public QuestionsRequestBody(int a, int id) {
            this.a = a;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuestionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QuestionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference1.QuestionsResponseBody Body;
        
        public QuestionsResponse() {
        }
        
        public QuestionsResponse(ConsoleApplication1.ServiceReference1.QuestionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QuestionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QuestionsResult;
        
        public QuestionsResponseBody() {
        }
        
        public QuestionsResponseBody(string QuestionsResult) {
            this.QuestionsResult = QuestionsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsoleApplication1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.WebService1Soap>, ConsoleApplication1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.AnswerResponse ConsoleApplication1.ServiceReference1.WebService1Soap.Answer(ConsoleApplication1.ServiceReference1.AnswerRequest request) {
            return base.Channel.Answer(request);
        }
        
        public string Answer(int a, int id) {
            ConsoleApplication1.ServiceReference1.AnswerRequest inValue = new ConsoleApplication1.ServiceReference1.AnswerRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.AnswerRequestBody();
            inValue.Body.a = a;
            inValue.Body.id = id;
            ConsoleApplication1.ServiceReference1.AnswerResponse retVal = ((ConsoleApplication1.ServiceReference1.WebService1Soap)(this)).Answer(inValue);
            return retVal.Body.AnswerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.AnswerResponse> ConsoleApplication1.ServiceReference1.WebService1Soap.AnswerAsync(ConsoleApplication1.ServiceReference1.AnswerRequest request) {
            return base.Channel.AnswerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.AnswerResponse> AnswerAsync(int a, int id) {
            ConsoleApplication1.ServiceReference1.AnswerRequest inValue = new ConsoleApplication1.ServiceReference1.AnswerRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.AnswerRequestBody();
            inValue.Body.a = a;
            inValue.Body.id = id;
            return ((ConsoleApplication1.ServiceReference1.WebService1Soap)(this)).AnswerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.QuestionsResponse ConsoleApplication1.ServiceReference1.WebService1Soap.Questions(ConsoleApplication1.ServiceReference1.QuestionsRequest request) {
            return base.Channel.Questions(request);
        }
        
        public string Questions(int a, int id) {
            ConsoleApplication1.ServiceReference1.QuestionsRequest inValue = new ConsoleApplication1.ServiceReference1.QuestionsRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.QuestionsRequestBody();
            inValue.Body.a = a;
            inValue.Body.id = id;
            ConsoleApplication1.ServiceReference1.QuestionsResponse retVal = ((ConsoleApplication1.ServiceReference1.WebService1Soap)(this)).Questions(inValue);
            return retVal.Body.QuestionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.QuestionsResponse> ConsoleApplication1.ServiceReference1.WebService1Soap.QuestionsAsync(ConsoleApplication1.ServiceReference1.QuestionsRequest request) {
            return base.Channel.QuestionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.QuestionsResponse> QuestionsAsync(int a, int id) {
            ConsoleApplication1.ServiceReference1.QuestionsRequest inValue = new ConsoleApplication1.ServiceReference1.QuestionsRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.QuestionsRequestBody();
            inValue.Body.a = a;
            inValue.Body.id = id;
            return ((ConsoleApplication1.ServiceReference1.WebService1Soap)(this)).QuestionsAsync(inValue);
        }
    }
}
